language: go
go: "1.13"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE=api

script: 
  - docker run --rm -v "$PWD":/go/src/api -w /go/src/api golang:1.13-alpine go build -o api
  - docker build -f Dockerfile -t $IMAGE:$COMMIT ./

deploy:
  provider: script  
  script: bash deploy.sh
  on:
    all_branches: true
